
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dive-sites_development

test:
  <<: *default
  database: dive-sites_test

production:
  <<: *default
  database: dive-sites_production
  username: dive-sites
  password: <%= ENV['DIVE-SITES_DATABASE_PASSWORD'] %>
